<?php
$colors = array('purple', 'yellow', 'green', 'blue', 'red', 'darkblue');
?>
<div class="grid_10">
  <div class="box round first">
    <h2>
      Product Sales</h2>

    <div class="block">
      <div id="chart1">
      </div>
    </div>
  </div>
  <div class="box round">
    <h2>
      Type
    </h2>

    <div class="block">
      <div id='cssmenu' style="float: left; display: inline; border-width: 0px;">
        <ul>
          <?php
          if (!empty($this->dailyexpensesType)) {
            foreach ($this->dailyexpensesType as $value) {
              echo '<li><a class="' . $value->getName() . '"><span>' . $value->getName() . '</span></a></li>';
            }
          }

          ?>
        </ul>
      </div>
      <?php
      if (!empty($this->dailyexpensesType)) {
        foreach ($this->dailyexpensesType as $value) {
          echo '<input type="hidden" id="dailyExpenseType' . $value->getName() . '" value="' . $value->getName() . '"  />';
        }
      }

      ?>
      <div id="expensive-outPut" style="float:left; margin-left: 20px; display: inline">
        asdfasdf
      </div>

    </div>

    <div class="clear">
    </div>
  </div>

</div>
