<?php echo $this->doctype(); ?>
<html lang="en">
<head>
  <meta charset="utf-8">
  <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>
  <!-- Le styles -->
  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/style.css');
  ?>
  <!-- Scripts -->
  <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/init.js')
    ->prependFile($this->basePath() . '/js/jquery.js')
    ->prependFile($this->basePath() . '/js/skel.min.js');
  ?>

  <script type="text/javascript">
    jQuery.browser = {};
    (function () {
      jQuery.browser.msie = false;
      jQuery.browser.version = 0;
      if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
        jQuery.browser.msie = true;
        jQuery.browser.version = RegExp.$1;
      }
    })();
    $(document).ready(function () {
    //  setupLeftMenu();
   //   setSidebarHeight();
   //   $('#example').dataTable();
      /* assuming that text input datePicker would have id='datePicker' */
  //    $("#datePicker").datepicker({ dateFormat: 'dd/mm/yy' });
    //  $("#expensive-outPut").css("visibility", "hidden");
    //  $("#cssmenu a").click(function () {
    //    var id = $(this).attr('class');
     //   var value = $(this).attr('value');
      //  $("#expensive-outPut").css("visibility", "visible");
       // $("#expensive-outPut form #type_id").attr('value', id)
       // $("#expensive-outPut .form-sub-title").text(value);
      });
    });
  </script>
</head>
<body class="homepage">

<!-- Wrapper-->
<div id="wrapper">
  <!-- Nav -->
  <nav id="nav">
    <a href="#me" class="fa fa-home active"><span>Home</span></a>
    <a href="#work" class="fa fa-folder"><span>Work</span></a>
    <a href="#email" class="fa fa-envelope"><span>Email Me</span></a>
    <a href="http://twitter.com/n33co" class="fa fa-twitter"><span>Twitter</span></a>
  </nav>
  <!-- Main -->
  <?php echo $this->content; ?>
  <!-- Footer -->
  <div id="footer">
    <ul class="links">
      <li>&copy; Jane Doe</li>
      <li>Images : <a href="http://fotogrph.com/">fotogrph</a></li>
      <li>Design : <a href="http://html5up.net/">HTML5 UP</a></li>
    </ul>
  </div>
</div>
</body>
</html>